version: '3.5'

services:

  wordpress:
    image: wordpress #specify the img_name in WP directory
    build: ./wordpress #build option to build image from WP directory
    volumes:
        - wordpress_vol:/var/www/html/wordpress
    environment:
        - MARIADB_USER
        - MARIADB_PWD
        - MARIADB_HOST
        - MYSQL_ROOT_PASSWORD
        - DB_HOST
        - USERNAME_WP
        - WORDPRESS_DB_NAME
        - ADMIN_USER_WP
        - ADMIN_PWD_WP
        - ADMIN_MAIL_WP
        - URL_WP

    links:
        - mariadb
    restart: always
    ports:
        - '9000:9000'
    networks: 
        - inception

  nginx:
    image: nginx
    build: ./nginx
    ports:
        - '443:443'
    volumes:
        - wordpress_vol:/var/www/html/wordpress
    links:
        - wordpress
    restart: always
    networks: 
        - inception

  mariadb:
    image: mariadb
    build: ./mariadb
    env_file: .env
    volumes:
        - mariadb:/var/lib/mysql
    restart: always
    environment:
        - MARIADB_USER
        - MYSQL_ROOT_PASSWORD
        - WORDPRESS_DB_NAME
        - MARIADB_PWD
        - MARIADB_ROOT_PWD
        - USERNAME_WP
    ports:
        - '3306:3306'
    networks: 
        - inception

volumes:
    wordpress_vol:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/defaultuser/data/wordpress_vol'
    mariadb:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/defaultuser/data/database'
    
networks:
    inception:
        name: inception
        driver: bridge