FROM	debian:buster

# UPDATE & UPGRADE THE SYSTEM
RUN		apt-get update -y \
&&		apt-get upgrade -y

# INSTALL NGINX
RUN		apt-get install -y nginx \
&&		apt-get install -y openssl

RUN mkdir -p /etc/ssl/certs
RUN mkdir -p /var/log/nginx

RUN openssl req -newkey rsa:4096 \
    -x509 \
    -sha256 \
    -days 3650 \
    -nodes \
    -out /etc/ssl/certs/pmulin.42.fr.crt \
    -keyout /etc/ssl/certs/pmulin.42.fr.key \
    -subj "/C=FR/ST=Lyon/L=Lyon/O=42/OU=pmulin Department/CN=www.pmulin.42.fr"

COPY /conf/nginx.conf /etc/nginx/sites-available/pmulin.42.fr.conf

RUN ln -s /etc/nginx/sites-available/pmulin.42.fr.conf /etc/nginx/sites-enabled/pmulin.42.fr.conf

EXPOSE 443

ENTRYPOINT ["nginx", "-g", "daemon off;"]