FROM debian:buster

RUN apt update && \
    apt install mariadb-server -y

COPY ./test.sh ./

RUN chmod +x test.sh

RUN	sed -i 's/bind-address/bind-address = 0.0.0.0 #/i' /etc/mysql/mariadb.conf.d/50-server.cnf

EXPOSE 3306

ENTRYPOINT [ "./test.sh" ]