FROM debian:buster

RUN apt update -y && \
    apt upgrade -y && \
    apt install mariadb-client -y \
    && apt-get install -y php-fpm php-mysql \
    && apt-get install wget -y

RUN		service php7.3-fpm start && service php7.3-fpm stop
RUN		sed -i "s/\/run\/php\/php7.3-fpm.sock/wordpress:9000/" /etc/php/7.3/fpm/pool.d/www.conf

#installing CLI
RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar; \
 	mv wp-cli.phar /usr/local/bin/wp

RUN mkdir -p /var/www/html/wordpress

RUN chown -R www-data:www-data /var/www/html/wordpress
RUN chown www-data:www-data /var/www/html/wordpress
RUN chmod 755 /var/www/html/wordpress

WORKDIR /var/www/html/wordpress

COPY ./test.sh ./

RUN chmod +x test.sh

EXPOSE 9000

ENTRYPOINT [ "./test.sh" ]